# Generated by Django 4.1 on 2024-03-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookatable', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
